filetype off
set runtimepath^=~/.vim/plugged/vader.vim
set runtimepath+=~/.vim/plugged/vim-cs
filetype plugin indent on
syntax enable
set nomore noswapfile
set viminfo=
set expandtab shiftwidth=4 softtabstop=-1
