if &compatible
  set nocompatible
endif

filetype off

" Assuming that plugins are installed in the same folder, e.g. ~/.vim/plugged
let plugindir = expand("\<sfile>:h:h:h")

" Dependency to vader.vim
let &runtimepath = plugindir . '/vim-cs,' . &runtimepath
let &runtimepath .= ',' . plugindir . '/vader.vim'

filetype plugin indent on
syntax enable

set nomore noswapfile
set viminfo=
set expandtab shiftwidth=4 softtabstop=-1
